server:
  port: 8081

spring:
  application:
    name: broker-java

ctf:
  jwt:
    secret: ${CTF_JWT_SECRET:change-this-super-long-dev-secret-for-jwt-1234567890}
  broker:
    idle-timeout-seconds: ${CTF_BROKER_IDLE_TIMEOUT_SECONDS:900}
